# Entorno: Producción

# Utiliza una imagen base adecuada para tu aplicación en el entorno de producción
FROM golang:alpine

# Copia los archivos necesarios de tu aplicación al contenedor
COPY . /app

# Establece el directorio de trabajo
WORKDIR /app

# Instala las dependencias de tu aplicación
RUN go mod download

# Expone el puerto necesario para tu aplicación
EXPOSE 3000

# Ejecuta el comando para iniciar tu aplicación en el entorno de producción
CMD ["./main"]