# Entorno: Desarrollo

# Utiliza una imagen base adecuada para tu aplicación en el entorno de desarrollo
FROM golang:alpine

# Copia los archivos necesarios de tu aplicación al contenedor
COPY . /app

# Establece el directorio de trabajo
WORKDIR /app

# Instala las dependencias de tu aplicación
RUN go mod download

# Exponer el puerto 3000 para acceder a la aplicación en el entorno de desarrollo
EXPOSE 3000

# Ejecuta tu aplicación
CMD ["go", "run", "main.go"]